name: manage-azure-policy-33fa236a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Log_Analytics_workspace_1f6e93e8-6b31-41b1-83f6-36e449a42579/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_237e0f7e-b0e8-4ec4-ad46-8c12cb66d673/**'
#      - 'Policies/policies/Configure_Azure_Activity_logs_to_stream_to_specified_Log_Analytics_workspace_2465583e-4e78-4c15-b6be-a36cbc7c8b0f/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Data_Lake_Storage_Gen1_to_Log_Analytics_workspace_25763a0a-5783-4f14-969e-79d4933eb74b/**'
#      - 'Policies/policies/Configure_diagnostic_settings_for_storage_accounts_to_Log_Analytics_workspace_6f8f98a4-f108-47cb-8e98-91a0d85cd474/**'
#      - 'Policies/policies/Configure_Azure_SQL_database_servers_diagnostic_settings_to_Log_Analytics_workspace_7ea8a143-05e3-4553-abfe-f56bef8b0b70/**'
#      - 'Policies/policies/Deploy_-_Configure_diagnostic_settings_to_a_Log_Analytics_workspace_to_be_enabled_on_Azure_Key_Vault_Managed_HSM_b3884c81-31aa-473d-a9bb-9466fe0ec2a0/**'
#      - 'Policies/policies/Deploy_-_Configure_diagnostic_settings_for_SQL_Databases_to_Log_Analytics_workspace_b79fa14e-238a-4c2d-b376-442ce508fc84/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Recovery_Services_Vault_to_Log_Analytics_workspace_for_resource_specific_categories._c717fb0c-d118-4c43-ab3d-ece30ac81fb3/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Log_Analytics_workspace_c84e5349-db6d-4769-805e-e14037dab9b5/**'
#      - 'Policies/policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Storage/storageAccounts_(Storage)_to_a_Log_Analytics_Workspace_0231FCA785ED25776C9924503CF8B1EB/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.KeyVault/vaults_to_a_Log_Analytics_Workspace_05EE701865C5EF359979ED0C591C8928/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Logic/workflows_to_a_Log_Analytics_Workspace_0D32F82FC3AB649805888236FD965BE8/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/virtualNetworks_to_a_Log_Analytics_Workspace_103941B66EFD5882F03DEBBC8AC4C9A8/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/networkInterfaces_to_a_Log_Analytics_Workspace_204F3D038AD9D98BBF748C311CDBC999/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.RecoveryServices/vaults_to_a_Log_Analytics_Workspace_21F57A48443C0A60112B8A2C96ED1E5D/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.OperationalInsights/workspaces_to_a_Log_Analytics_Workspace_3CB68922AFF76C909E2D2AA3A4D9217F/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Storage/storageAccounts_(StorageV2)_to_a_Log_Analytics_Workspace_4D3CF186A40A7C2C481B645A540C1C7C/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/publicIPAddresses_to_a_Log_Analytics_Workspace_69236DBA82C8CBFBD4F0FA62344CCA83/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/networkSecurityGroups_to_a_Log_Analytics_Workspace_C2E942DD7954DEB73491254DFA3FCB80/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/loadBalancers_to_a_Log_Analytics_Workspace_C89F5030DC8C4DD0F88D3B6C629D897A/**'
#      - 'Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Compute/virtualMachines_to_a_Log_Analytics_Workspace_E84B8271527313D90DC8E190C39FF74B/**'
#      - 'Policies/policies/The_Log_Analytics_agent_should_be_installed_on_Virtual_Machine_Scale_Sets_efbde977-ba53-4479-b8e9-10b957924fbf/**'
#      - 'Policies/policies/The_Log_Analytics_agent_should_be_installed_on_virtual_machines_a70ca396-0a34-413a-88e1-b956c1e683be/**'
#      - 'Policies/policies/Log_Analytics_agent_should_be_installed_on_your_virtual_machine_for_Azure_Security_Center_monitoring_a4fe33eb-e377-4efb-ab31-0784311bc499/**'
#      - 'Policies/policies/Log_Analytics_agent_should_be_installed_on_your_virtual_machine_scale_sets_for_Azure_Security_Center_monitoring_a3a6ea0c-e018-4933-9ef0-5aaa1501449b/**'
#      - 'Policies/policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Key_Vault_to_Log_Analytics_workspace_951af2fa-529b-416e-ab6e-066fd85ac459/**'
#      - 'Policies/policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Kubernetes_Service_to_Log_Analytics_workspace_6c66c325-74c8-42fd-a286-a74b0e2939d8/**'
#      - .github/workflows/manage-azure-policy-33fa236a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_33fa236a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Policies/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Log_Analytics_workspace_1f6e93e8-6b31-41b1-83f6-36e449a42579/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_237e0f7e-b0e8-4ec4-ad46-8c12cb66d673/**
          Policies/policies/Configure_Azure_Activity_logs_to_stream_to_specified_Log_Analytics_workspace_2465583e-4e78-4c15-b6be-a36cbc7c8b0f/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Data_Lake_Storage_Gen1_to_Log_Analytics_workspace_25763a0a-5783-4f14-969e-79d4933eb74b/**
          Policies/policies/Configure_diagnostic_settings_for_storage_accounts_to_Log_Analytics_workspace_6f8f98a4-f108-47cb-8e98-91a0d85cd474/**
          Policies/policies/Configure_Azure_SQL_database_servers_diagnostic_settings_to_Log_Analytics_workspace_7ea8a143-05e3-4553-abfe-f56bef8b0b70/**
          Policies/policies/Deploy_-_Configure_diagnostic_settings_to_a_Log_Analytics_workspace_to_be_enabled_on_Azure_Key_Vault_Managed_HSM_b3884c81-31aa-473d-a9bb-9466fe0ec2a0/**
          Policies/policies/Deploy_-_Configure_diagnostic_settings_for_SQL_Databases_to_Log_Analytics_workspace_b79fa14e-238a-4c2d-b376-442ce508fc84/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Recovery_Services_Vault_to_Log_Analytics_workspace_for_resource_specific_categories._c717fb0c-d118-4c43-ab3d-ece30ac81fb3/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Log_Analytics_workspace_c84e5349-db6d-4769-805e-e14037dab9b5/**
          Policies/policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Storage/storageAccounts_(Storage)_to_a_Log_Analytics_Workspace_0231FCA785ED25776C9924503CF8B1EB/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.KeyVault/vaults_to_a_Log_Analytics_Workspace_05EE701865C5EF359979ED0C591C8928/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Logic/workflows_to_a_Log_Analytics_Workspace_0D32F82FC3AB649805888236FD965BE8/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/virtualNetworks_to_a_Log_Analytics_Workspace_103941B66EFD5882F03DEBBC8AC4C9A8/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/networkInterfaces_to_a_Log_Analytics_Workspace_204F3D038AD9D98BBF748C311CDBC999/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.RecoveryServices/vaults_to_a_Log_Analytics_Workspace_21F57A48443C0A60112B8A2C96ED1E5D/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.OperationalInsights/workspaces_to_a_Log_Analytics_Workspace_3CB68922AFF76C909E2D2AA3A4D9217F/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Storage/storageAccounts_(StorageV2)_to_a_Log_Analytics_Workspace_4D3CF186A40A7C2C481B645A540C1C7C/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/publicIPAddresses_to_a_Log_Analytics_Workspace_69236DBA82C8CBFBD4F0FA62344CCA83/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/networkSecurityGroups_to_a_Log_Analytics_Workspace_C2E942DD7954DEB73491254DFA3FCB80/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Network/loadBalancers_to_a_Log_Analytics_Workspace_C89F5030DC8C4DD0F88D3B6C629D897A/**
          Policies/policies/Apply_Diagnostic_Settings_for_Microsoft.Compute/virtualMachines_to_a_Log_Analytics_Workspace_E84B8271527313D90DC8E190C39FF74B/**
          Policies/policies/The_Log_Analytics_agent_should_be_installed_on_Virtual_Machine_Scale_Sets_efbde977-ba53-4479-b8e9-10b957924fbf/**
          Policies/policies/The_Log_Analytics_agent_should_be_installed_on_virtual_machines_a70ca396-0a34-413a-88e1-b956c1e683be/**
          Policies/policies/Log_Analytics_agent_should_be_installed_on_your_virtual_machine_for_Azure_Security_Center_monitoring_a4fe33eb-e377-4efb-ab31-0784311bc499/**
          Policies/policies/Log_Analytics_agent_should_be_installed_on_your_virtual_machine_scale_sets_for_Azure_Security_Center_monitoring_a3a6ea0c-e018-4933-9ef0-5aaa1501449b/**
          Policies/policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Key_Vault_to_Log_Analytics_workspace_951af2fa-529b-416e-ab6e-066fd85ac459/**
          Policies/policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Kubernetes_Service_to_Log_Analytics_workspace_6c66c325-74c8-42fd-a286-a74b0e2939d8/**
